version: '3.0'

services:
  nextcloud:
    container_name: nextcloud-pdlib
    build: ./pdlib
    ports:
      - 50080:80/tcp
    environment:
      - DLIB_TAG=${DLIB_TAG:-v19.19}
      - PDLIB_BRANCH=${PDLIB_BRANCH:-master}
      - FR_TAG=${FR_TAG:-v0.9.5}
    volumes:
      - './nextcloud-html:/var/www/html'
    restart: unless-stopped
  cron:
    container_name: nextcloud-cron
    build: ./pdlib
    restart: unless-stopped
    volumes:
      - './nextcloud-html:/var/www/html'
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
